####################################################################
# VSTS Build Configuration, Version 1.2
#
# (c)2018 superdev GmbH
####################################################################

name: 1.0.$(date:yy)$(DayOfYear).$(rev:rr)
  
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
  - vstest

trigger:
  branches:
    include:
    - master
    - develop
    - releases/*

  paths:
    include:
    - docs/*
    exclude:
    - docs/README.md

variables:
  solution: 'NuGetCleaner.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildVersionPostfix: '-pre'

steps:
- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-Task.Assembly-Info-Task@1
  displayName: 'Set Assembly Manifest Data'
  inputs:
    FileNames: |
     AssemblyInfo.cs
    InsertAttributes: true
    Title: 'NuGetCleaner'
    Description: ''
    Company: 'superdev GmbH'
    Copyright: '(c) $(date:yyyy) superdev GmbH'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    msbuildArgs: ''
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     **\bin\$(BuildConfiguration)\**
     **\bin\*.exe
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    flattenFolders: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)' 
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/NuGetCleaner_$(Build.BuildNumber).zip' 
    replaceExistingArchive: true 

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
